name: Docker CI

on:
  push:
    branches:
      - main # or your default branch, e.g., master
  pull_request:
    branches:
      - main # or your default branch, e.g., master

jobs:
  build-and-test-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # This permission is required to push to GitHub Container Registry

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Define image name and tag
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }} # ghcr.io/owner/repo-name
        tags: |
          type=sha
          type=ref,event=branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} # Tag 'latest' only on default branch

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Adjust if your Dockerfile is not in the root
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run tests inside Docker container (optional - after push or before push)
      # This step assumes the image is already pushed and available, or built locally.
      # If you prefer to test the locally built image before pushing, move this step
      # before the 'Build and push Docker image' step and adjust the image name.
      # Example: docker run ghcr.io/${{ github.repository }}:latest your-test-command-here
      # Or, if testing before push: docker run ${{ steps.meta.outputs.tags }} your-test-command-here
      run: |
        IMAGE_TAG=${{ steps.meta.outputs.tags }}
        # If testing after push, you might pull the image first to ensure you're testing what's pushed
        # docker pull $IMAGE_TAG
        docker run $IMAGE_TAG your-test-command-here